### ISSUE TITLE
Change room temperature?

### ISSUE THREAD

**Issue by robot300795** [bullitt186/ha-stiebel-control#1]
Is it possible to change the room temperature for the heat pump which is sent for example from the FEK and is important for cooling? I would like to send the heat pump the lowest temperature of all rooms.

**Comment by bullitt186** [comment]
Not out of the box, currently.
there are several signals such as RAUMISTTEMP, RAUMSOLLTEMP, RAUMSOLLTEMP_NACHT and VERSTELLTE_RAUMSOLLTEMP, so it should be possible in theory. However on my 2023 WPL13e (without cooling function) and a simple FE7 instead of a more advanced FEK, I only got -255 (SNA) for RAUMISTTEMP, so I cannot test this out properly.
I see the issue if we send out RAUMISTTEMP via Home Assistant, it would be overwritten by the SNA RAUMISTTEMP on the CAN Bus. Maybe one could deactivate the FEK completely but I have not tested this. 

If you want to test yourself: To add the writing capabilities to the raumtemperatures, you simply have to add entries in the ha_stiebel_control.yaml, such as:
```YAML
input_number:
  speichersolltemp2_set:
    name: "SPEICHERSOLLTEMP2_SET"
    initial: 20
    min: 20
    max: 60
    mode: box
    step: 1
    unit_of_measurement: "°C"
    icon: mdi:thermometer-low
```
and in the esphome sketch:
```yaml
  - platform: homeassistant
    name: "EINSTELL_SPEICHERSOLLTEMP2_SET"
    id: EINSTELL_SPEICHERSOLLTEMP2_SET
    entity_id: input_number.speichersolltemp2_set
    on_value:
      then:
        lambda: |-
          if(atoi(x.c_str()) != 20) {
            char temp[3];
            strncpy(temp, x.c_str(), sizeof(temp)-1);
            temp[2] ='\0';
            const char* ctemp = temp;
            writeSignal(&CanMembers[cm_manager], GetElsterIndex("EINSTELL_SPEICHERSOLLTEMP2"), ctemp);
            id(EINSTELL_SPEICHERSOLLTEMP2).update();
            id(SPEICHERISTTEMP).update();
            id(SPEICHERSOLLTEMP).update();
          }
          return;
```

In case you do so, let me know the results of your investigation
